// TaskTrackerApi/Services/Implementations/TaskPdfExporter.cs

using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace TaskTrackerApi.Services.Implementations
{
    public class TaskPdfExporter
    {
        public byte[] GenerateTasksPdf(IEnumerable<TaskDto> tasks, bool isincludeOwnerEmailAdmin)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.Header().Text("Task List").FontSize(20).Bold().AlignCenter();
                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();

                            if (isincludeOwnerEmailAdmin)
                                columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Title").Bold();
                            header.Cell().Text("Description").Bold();
                            header.Cell().Text("Due Date").Bold();
                            header.Cell().Text("Completed").Bold();
                            if (isincludeOwnerEmailAdmin)
                                header.Cell().Text("Owner Email").Bold();
                        });

                        foreach (var task in tasks)
                        {
                            table.Cell().Text(task.Title);
                            table.Cell().Text(task.Description);
                            table.Cell().Text(task.DueDate.ToShortDateString());
                            table.Cell().Text(task.IsCompleted ? "Yes" : "No");
                            if (isincludeOwnerEmailAdmin)
                                table.Cell().Text(task.OwnerEmail ?? "");
                        }
                    });

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Generated by TaskTracker");
                    });
                });
            });

            using var stream = new MemoryStream();
            document.GeneratePdf(stream);
            return stream.ToArray();
        }
    }
}
