// TaskTrackerApi/Services/Implementations/UserListPdfExporter.cs

using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TaskTrackerApi.DTOs;

namespace TaskTrackerApi.Services.Implementations
{
    public class UserListPdfExporter
    {
        public byte[] GenerateUsersPdf(IEnumerable<UserDto> users)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.Header().Text("User List").FontSize(20).Bold().AlignCenter();
                    page.Content().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("User Name").Bold();
                            header.Cell().Text("Email").Bold();
                            header.Cell().Text("Roles").Bold();
                        });

                        foreach (var user in users)
                        {
                            table.Cell().Text(user.UserName);
                            table.Cell().Text(user.Email);
                            table.Cell().Text(string.Join(", ", user.Roles));
                        }
                    });

                    page.Footer().AlignCenter().Text("Generated by TaskTracker");
                });
            });

            using var stream = new MemoryStream();
            document.GeneratePdf(stream);
            return stream.ToArray();
        }
    }
}
